spring:
  config:
    import:
      - classpath:application-default.yaml
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

sentry:
  dsn: ${SENTRY_DSN}
  max-request-body-size: always
  send-default-pii: true
  traces-sample-rate: 1.0
