server:
  forward-headers-strategy: NATIVE
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    log-resolved-exception: false
  jpa:
    open-in-view: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
