spring:
  config:
    import:
      - classpath:application.yaml
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/test}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:default}
      database: ${REDIS_DATABASE:0}
  opensearch:
    scheme: ${OPENSEARCH_SCHEME:http}
    host: ${OPENSEARCH_HOST:localhost}
    port: ${OPENSEARCH_PORT:9200}
    username: ${OPENSEARCH_USERNAME:admin}
    password: ${OPENSEARCH_PASSWORD:admin}

logging:
  level:
    org.mongodb.driver.protocol.command: info