spring:
  config:
    import:
      - classpath:application.yaml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:zighang_zighang}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:default}
      database: ${REDIS_DATABASE:0}
  opensearch:
    scheme: ${OPENSEARCH_SCHEME:http}
    host: ${OPENSEARCH_HOST:localhost}
    port: ${OPENSEARCH_PORT:9200}
    username: ${OPENSEARCH_USERNAME:admin}
    password: ${OPENSEARCH_PASSWORD:admin}
