package com.github.zighang_zighang.domain.recruitment.constant.직군;

public enum 미디어_엔터 implements 직군 {
    PD_감독,
    콘텐츠기획_에디터,
    방송작가,
    촬영감독_카메라,
    영상편집,
    CG_모션그래픽,
    사운드디자이너,
    기자_리포터,
    아나운서_쇼호스트,
    성우_나래이터,
    크리에이터_인플루언서,
    모델_연기자,
    사진작가,
    방송기술_중계,
    송출_편성,
    아티스트매니지먼트,
    배급_제작사,
    음원_음반,
    웹툰_웹소설,
    출판,
    통_번역,
    기타_미디어_엔터,
}
